# Generated by Django 5.1.4 on 2025-01-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_unique_together_alter_workout_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='day',
        ),
    ]
