# Generated by Django 5.1.4 on 2025-01-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_trainer'),
        ('workouts', '0006_day_alter_workout_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='members.member'),
        ),
    ]
