# Generated by Django 5.1.4 on 2025-01-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_trainer'),
        ('trainer', '0001_initial'),
        ('workouts', '0008_alter_workout_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.day'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.trainer'),
        ),
    ]
