# Generated by Django 5.1.4 on 2025-01-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_trainer'),
        ('workouts', '0009_alter_workout_day_alter_workout_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='members.member'),
        ),
    ]
