# Generated by Django 5.1 on 2024-09-02 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='sarting_date',
        ),
        migrations.AddField(
            model_name='member',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
