# Generated by Django 5.1 on 2024-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='starting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
