# Generated by Django 5.1 on 2024-09-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pending_amount',
            field=models.FloatField(null=True),
        ),
    ]
