# Generated by Django 5.1 on 2024-09-28 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_pending_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
