# Generated by Django 5.1 on 2024-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
