# Generated by Django 5.1.4 on 2025-01-12 08:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0010_alter_member_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, help_text='Body fat percentage', null=True)),
                ('muscle_mass', models.FloatField(blank=True, help_text='Muscle mass in kg', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional progress notes', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='members.member')),
            ],
        ),
    ]
