# Generated by Django 5.1.4 on 2025-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
    ]
